### ISSUE TITLE
i got this error when i creat reactapp

### ISSUE THREAD

**Issue by Mohamedmahrous995** [lydell/urix#2]
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/frontend/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /usr/local/lib/node_modules/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/usr/local/lib/node_modules/frontend/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@15.11.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /usr/local/lib/node_modules/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:200:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/frontend/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/frontend/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/usr/local/lib/node_modules/frontend/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/frontend/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/frontend/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/frontend/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:200:21)
npm ERR! gyp ERR! System Linux 5.8.0-44-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/frontend/node_modules/node-sass
npm ERR! gyp ERR! node -v v15.11.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-06T03_08_45_129Z-debug.log

**Comment by lydell** [comment]
Hi! [npm-why](https://github.com/amio/npm-why#readme) or [yarn why](https://classic.yarnpkg.com/en/docs/cli/why/) are great tools for figuring out why you depend on a certain package.

`yarn why` tells me the dependency chain for create-react-app is:

```
react-scripts > resolve-url-loader > rework > css > urix
```

resolve-url-loader is working on getting rid of rework: https://github.com/bholloway/resolve-url-loader/issues/160

So you’ll need to wait for that, and then for react-scripts to update resolve-url-loader!
